language: emacs-lisp
dist: trusty
# https://github.com/travis-ci/travis-ci/issues/9061
sudo: required
matrix:
  allow_failures:
    - env: EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.3
    - env: EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.5
env:
  - EMACS_VERSION=26.1 ZMQ_VERSION=4.2.3
  - EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.3
  - EMACS_VERSION=26.1 ZMQ_VERSION=4.2.5
  - EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.5
before_install:
  # Setup paths
  - export PATH=${TRAVIS_BUILD_DIR}/.evm/bin:${TRAVIS_BUILD_DIR}/.cask/bin:${PATH}
  - sudo apt-get update
  # Install emacs
  - if [[ ${EMACS_VERSION} = git-snapshot ]]; then sudo apt-get install -y texinfo; fi
  # Use this fork of EVM for dynamic module support
  - git clone https://github.com/ubolonton/evm ${TRAVIS_BUILD_DIR}/.evm
  - evm config path /tmp
  - evm install emacs-${EMACS_VERSION} --use --skip
  # Install cask
  - git clone https://github.com/cask/cask ${TRAVIS_BUILD_DIR}/.cask
install:
  - sudo apt-get install -y python3 python3-pip
  - sudo pip3 install --upgrade setuptools pip
  # --ignore-installed six since jupyter tries to upgrade it, but it can't be
  # ugraded since it is a distutils package
  - sudo pip3 install --ignore-installed six jupyter
  # Install the kernelspec using the right python. Jupyter installs a default
  # python kernelspec that uses "python" for the command in
  # /usr/local/share/jupyter. This installs one with an absolute path using our
  # python3
  - sudo python3 -m ipykernel.kernelspec
  - cd $TRAVIS_BUILD_DIR
  - make dev
script:
  - cd $TRAVIS_BUILD_DIR
  # Ensure Jupyter runtime dir can be written to
  - mkdir -p $(jupyter --runtime-dir)
  - jupyter --runtime-dir
  - jupyter --paths
  - jupyter kernelspec list
  - make test
